name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - run: |
          published_version="$(npm show "$(node -pe 'require("./package.json").name')" version)"
          local_version="$(node -pe 'require("./package.json").version')"
          if [[ published_version != local_version ]]; then
            echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' >.npmrc
            npm ci
            npm publish
          fi
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
