name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Publish NPM package
        uses: pascalgn/npm-publish-action@1.3.3
        env:
          GITHUB_OTKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
